listen              1935;
max_connections     1000;
daemon              off;

http_server {
    enabled on;
    listen 8080;
}

http_api {
    enabled on;
    listen 1985;
}

vhost __defaultVhost__ {

    hls {
        enabled on;
        hls_path ./objs/nginx/html;
        hls_fragment 5;
        hls_window 30;
    }

    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }

    http_hooks {
        enabled         on;
        on_publish      http://backend:8081/api/srs/on-publish;
        on_unpublish    http://backend:8081/api/srs/on-unpublish;
        on_play         http://backend:8081/api/srs/on-play;
        on_stop         http://backend:8081/api/srs/on-stop;
    }
}